# Generated by Django 5.0.6 on 2024-05-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('MSV', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Hoten', models.CharField(max_length=50)),
                ('Ngaysinh', models.DateField()),
                ('Gioitinh', models.IntegerField()),
                ('CCCD', models.CharField(max_length=12)),
                ('Quequan', models.CharField(max_length=255)),
                ('SDT', models.CharField(blank=True, max_length=12)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Lopsinhhoat', models.CharField(max_length=10)),
                ('Nganhhoc', models.CharField(max_length=50)),
                ('Khoa', models.CharField(max_length=50)),
                ('Nienkhoa', models.CharField(max_length=9)),
                ('Dantoc', models.CharField(max_length=255)),
                ('Pass', models.CharField(max_length=50)),
            ],
        ),
    ]
