# Generated by Django 5.0.4 on 2024-05-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_thongtinsinhvien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='Gioitinh',
            field=models.IntegerField(choices=[(0, 'Nam'), (1, 'Nữ')], default=0),
        ),
    ]
