# Generated by Django 5.0.4 on 2024-05-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_thongtinsinhvien', '0003_alter_sinhvien_gioitinh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sinhvien',
            old_name='Pass',
            new_name='Matkhau',
        ),
    ]
