# Generated by Django 5.0.4 on 2024-05-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_thongtinsinhvien', '0004_rename_pass_sinhvien_matkhau'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
