# Generated by Django 5.0.4 on 2024-05-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_thongtinsinhvien', '0005_sinhvien_image_alter_sinhvien_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='Image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
