# Generated by Django 5.0.4 on 2024-05-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_thongtinsinhvien', '0006_alter_sinhvien_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='SDT',
            field=models.CharField(max_length=12),
        ),
    ]
