# Generated by Django 5.0.4 on 2024-05-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_thongtinsinhvien', '0007_alter_sinhvien_email_alter_sinhvien_sdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='Image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
