# Generated by Django 5.0.4 on 2024-05-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_thongtinsinhvien', '0010_alter_sinhvien_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='Image',
            field=models.ImageField(null=True, upload_to='avt/%y'),
        ),
    ]
