# Generated by Django 5.0.6 on 2024-05-18 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaiDienPhongBan',
            fields=[
                ('MNV', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Hoten', models.CharField(max_length=50)),
                ('Ngaysinh', models.DateField(blank=True, null=True)),
                ('Gioitinh', models.IntegerField(blank=True, null=True)),
                ('SDT', models.CharField(blank=True, max_length=12, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Roles', models.IntegerField()),
                ('Pass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoiTuongChinhSach',
            fields=[
                ('MDT', models.BigAutoField(primary_key=True, serialize=False)),
                ('Mota', models.TextField()),
                ('Mucmiengiam', models.BigIntegerField()),
                ('Thoigianhuong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HinhAnh',
            fields=[
                ('MHA', models.BigAutoField(primary_key=True, serialize=False)),
                ('TenHA', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiDoiTuongChinhSach',
            fields=[
                ('MLDT', models.IntegerField(primary_key=True, serialize=False)),
                ('Mota', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('MSV', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Hoten', models.CharField(max_length=50)),
                ('Ngaysinh', models.DateField()),
                ('Gioitinh', models.IntegerField()),
                ('CCCD', models.CharField(max_length=12)),
                ('Quequan', models.CharField(max_length=255)),
                ('SDT', models.CharField(blank=True, max_length=12, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Lopsinhhoat', models.CharField(max_length=10)),
                ('Nganhhoc', models.CharField(max_length=50)),
                ('Khoa', models.CharField(max_length=50)),
                ('Nienkhoa', models.CharField(max_length=9)),
                ('Dantoc', models.CharField(max_length=255)),
                ('Pass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TieuChi',
            fields=[
                ('MTC', models.BigAutoField(primary_key=True, serialize=False)),
                ('Mota', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('MBV', models.BigAutoField(primary_key=True, serialize=False)),
                ('Noidung', models.TextField()),
                ('Ngaydang', models.DateTimeField()),
                ('NgayhetHieuluc', models.DateTimeField()),
                ('MNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.daidienphongban')),
            ],
        ),
        migrations.CreateModel(
            name='HoSoDangKy',
            fields=[
                ('MHSDK', models.BigAutoField(primary_key=True, serialize=False)),
                ('MotaHoancanhKhokhan', models.CharField(blank=True, max_length=3000, null=True)),
                ('TrangthaiXacnhan', models.IntegerField(blank=True, null=True)),
                ('Ngaydangky', models.DateTimeField(blank=True, null=True)),
                ('Ngayxacnhan', models.DateTimeField(blank=True, null=True)),
                ('TrangthaiXetduyet', models.IntegerField(blank=True, null=True)),
                ('Ngayxetduyet', models.DateTimeField(blank=True, null=True)),
                ('Hocki', models.CharField(max_length=3)),
                ('MDT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doituongchinhsach')),
                ('MNV', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.daidienphongban')),
                ('MSV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sinhvien')),
            ],
        ),
        migrations.AddField(
            model_name='doituongchinhsach',
            name='MLDT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loaidoituongchinhsach'),
        ),
        migrations.CreateModel(
            name='HinhAnhBaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MBV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.baiviet')),
                ('MHA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hinhanh')),
            ],
            options={
                'unique_together': {('MHA', 'MBV')},
            },
        ),
        migrations.CreateModel(
            name='QuyDinhApDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MBV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.baiviet')),
                ('MDT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doituongchinhsach')),
                ('MTC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tieuchi')),
            ],
            options={
                'unique_together': {('MBV', 'MDT', 'MTC')},
            },
        ),
        migrations.CreateModel(
            name='ChiTietHoSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MHA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hinhanh')),
                ('MHSDK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hosodangky')),
                ('MTC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tieuchi')),
            ],
            options={
                'unique_together': {('MHSDK', 'MTC', 'MHA')},
            },
        ),
    ]
