# Generated by Django 4.2.13 on 2024-05-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sinhvien_ngaysinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='CCCD',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Dantoc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Gioitinh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Khoa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Lopsinhhoat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Nganhhoc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Nienkhoa',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Quequan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='SDT',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
