# Generated by Django 4.2.13 on 2024-05-19 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaiViet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baiviet',
            name='MHA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hinhanh', to='BaiViet.hinhanh'),
        ),
    ]
