# Generated by Django 4.2.13 on 2024-05-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaiViet', '0002_baiviet_mha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hinhanh',
            name='HA',
            field=models.ImageField(upload_to='BaiViet/static/app/assets/images'),
        ),
    ]
