# Generated by Django 4.2.13 on 2024-05-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaiViet', '0003_alter_hinhanh_ha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hinhanh',
            name='HA',
            field=models.ImageField(upload_to=''),
        ),
    ]
