# Generated by Django 4.2.13 on 2024-05-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaiViet', '0004_alter_hinhanh_ha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baiviet',
            name='MHA',
        ),
        migrations.AddField(
            model_name='baiviet',
            name='HA',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
