# Generated by Django 5.0.6 on 2024-05-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaiViet', '0005_remove_baiviet_mha_baiviet_ha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baiviet',
            old_name='HA',
            new_name='AnhBia',
        ),
        migrations.AddField(
            model_name='baiviet',
            name='TieuDe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
