# Generated by Django 5.0.6 on 2024-05-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaiViet', '0007_alter_baiviet_ngaydang_alter_baiviet_ngayhethieuluc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosodangky',
            name='MDT',
        ),
    ]
