# Generated by Django 5.0.6 on 2024-05-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaiViet', '0008_remove_hosodangky_mdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitiethoso',
            name='MTC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaiViet.tieuchi'),
        ),
    ]
