# Generated by Django 4.2.13 on 2024-06-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaiViet', '0013_alter_hosodangky_ngaydangky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosodangky',
            name='Ngayxetduyet',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
