# Generated by Django 5.0.6 on 2024-06-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaiViet', '0014_alter_hosodangky_ngayxetduyet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='Ngaydang',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='NgayhetHieuluc',
            field=models.DateTimeField(),
        ),
    ]
