# Generated by Django 5.0.6 on 2024-06-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaiViet', '0017_alter_baiviet_ngaydang_alter_baiviet_ngayhethieuluc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='Ngaydang',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='baiviet',
            name='NgayhetHieuluc',
            field=models.DateField(),
        ),
    ]
