# Generated by Django 4.2.13 on 2024-06-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaiViet', '0018_alter_baiviet_ngaydang_alter_baiviet_ngayhethieuluc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='CCCD',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Dantoc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Khoa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Lopsinhhoat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Nganhhoc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Ngaysinh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Nienkhoa',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Pass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='Quequan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
