# Generated by Django 5.0.6 on 2024-06-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanGiamHieu',
            fields=[
                ('MNV', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Hoten', models.CharField(max_length=50)),
                ('Ngaysinh', models.DateField()),
                ('Gioitinh', models.IntegerField(choices=[(0, 'Nam'), (1, 'Nữ')], default=0)),
                ('SDT', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Roles', models.IntegerField(choices=[(0, 'Hiệu Trưởng'), (1, 'Hiệu Phó')])),
                ('Matkhau', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='avt/%y')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bangiamhieu',
            constraint=models.UniqueConstraint(condition=models.Q(('Roles', 0)), fields=('Roles',), name='unique_hieu_truong'),
        ),
    ]
