# Generated by Django 5.0.6 on 2024-06-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_thongtinphongBGH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangiamhieu',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bangiamhieu',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='avt/%y'),
        ),
        migrations.AlterField(
            model_name='bangiamhieu',
            name='Ngaysinh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bangiamhieu',
            name='SDT',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
