# Generated by Django 5.0.4 on 2024-05-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_thongtinphongBGH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daidienphongban',
            name='Image',
            field=models.ImageField(null=True, upload_to='avt/%y'),
        ),
        migrations.AlterField(
            model_name='daidienphongban',
            name='Roles',
            field=models.IntegerField(choices=[(0, 'Hiệu Trưởng'), (1, 'Hiệu Phó')]),
        ),
    ]
