# Generated by Django 5.0.4 on 2024-05-31 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_thongtinphongBGH', '0002_daidienphongban_image_alter_daidienphongban_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DaiDienPhongBan',
            new_name='BanGiamHieu',
        ),
    ]
