# Generated by Django 4.2.13 on 2024-05-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240529_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='Ngaysinh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
