# Generated by Django 5.0.4 on 2024-05-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaiDienPhongBan',
            fields=[
                ('MNV', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Hoten', models.CharField(max_length=50)),
                ('Ngaysinh', models.DateField()),
                ('Gioitinh', models.IntegerField(choices=[(0, 'Nam'), (1, 'Nữ')])),
                ('SDT', models.CharField(blank=True, max_length=12)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Roles', models.IntegerField(choices=[(0, 'Hiệu Trưởng'), (1, 'Hiệu Phó'), (2, 'Phòng CTSV')])),
                ('Matkhau', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddConstraint(
            model_name='daidienphongban',
            constraint=models.UniqueConstraint(condition=models.Q(('Roles', 0)), fields=('Roles',), name='unique_hieu_truong'),
        ),
    ]
