# Generated by Django 5.0.4 on 2024-05-31 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_thongtinphongCTSV', '0002_remove_daidienphongban_unique_hieu_truong_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DaiDienPhongBan',
            new_name='PhongCTSV',
        ),
    ]
