# Generated by Django 5.0.4 on 2024-05-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_thongtinphongCTSV', '0003_rename_daidienphongban_phongctsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phongctsv',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='phongctsv',
            name='SDT',
            field=models.CharField(max_length=12),
        ),
    ]
