# Generated by Django 5.0.6 on 2024-06-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_thongtinphongCTSV', '0004_alter_phongctsv_email_alter_phongctsv_sdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phongctsv',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='phongctsv',
            name='Gioitinh',
            field=models.IntegerField(choices=[(0, 'Nam'), (1, 'Nữ')], default=0),
        ),
        migrations.AlterField(
            model_name='phongctsv',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='avt/%y'),
        ),
        migrations.AlterField(
            model_name='phongctsv',
            name='Ngaysinh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phongctsv',
            name='SDT',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
